### ISSUE TITLE
Install Options for nvChad lazy.nvim?

### ISSUE THREAD

**Issue by frankjonen** [wuelnerdotexe/vim-astro#6]
Just getting started with Neovim and this does nothing.

```lua
-- custom/plugins.lua
 {
    "wuelnerdotexe/vim-astro"
  },
```

Well, the plugin seems to be installed but nothing happens.
Hence my assumption that this probably isn't correct.

**Comment by frankjonen** [comment]
Got it to work (and mind you this is without an understanding of "why" yet).

```lua
-- custom/plugins.lua
  {
    "wuelnerdotexe/vim-astro",
    event = "InsertEnter",
  },
```

**Comment by wuelnerdotexe** [comment]
Hello! @frankjonen - To successfully run this plugin on [`NvChad`](https://github.com/NvChad/NvChad), you must specify the method to lazy load it, since in `NvChad` it is [enabled by default](https://github.com/NvChad/NvChad/blob/13e9b0f458c3e5e95ac05a10822f26dbb1aa03cb/lua/plugins/configs/lazy_nvim.lua#L2), unlike the [default `lazy.nvim`](https://github.com/folke/lazy.nvim#%EF%B8%8F-configuration) setting.

Having clarified the above, the standard method that I recommend for this plugin is the following:
```lua
-- custom/plugins.lua
  {
    "wuelnerdotexe/vim-astro",
    ft = "astro",
  },
```

If it now works as it should, could you please close this issue? Thank you :)

**Comment by frankjonen** [comment]
Hi @wuelnerdotexe I've just tried that. Using just `ft = "astro"` disables the plugin. `event = "InsertEnter"` seems to be like a global `bufenter`.

**Comment by frankjonen** [comment]
@wuelnerdotexe the interesting part is, the plugin only works in the preview, not when the file is opened in its own buffer. Then everything is just white text.

**Comment by frankjonen** [comment]
@wuelnerdotexe Got an error message that might be of use.

This happens when `event = "InsertEnter"` and I reload a file via `:e` or `:e %`

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...ocal/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: Error executing lua: ...ocal/Cellar/neovim/0.9.2/share/nvim/run
time/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[19]..script /Users/frank/.local/share/nvi
m/lazy/vim-astro/ftplugin/astro.vim[83]..function astro#CollectPathsFromConfig, line 9: Vim(let):E474: Unidentified byte: // Alias `src` to `~`     "baseUrl"
: ".",     "paths": {       "~/*": ["src/*"]     }   } }
stack traceback:
        [C]: in function 'nvim_cmd'
        ...ocal/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:25: in function <...ocal/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        ...ocal/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...ocal/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...ocal/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...ocal/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
```

**Comment by wuelnerdotexe** [comment]
Ok, @frankjonen - for some strange reason (which doesn't seem to be a problem with this plugin), the `ft="astro"` command (which should be the one) doesn't work (plain text) in `NvChad`, there the second option, I would recommend indicating `lazy = false` to load it as it would normally be done by default in Vim/Neovim.

**Comment by wuelnerdotexe** [comment]
> Got an error message that might be of use.
> 
> This happens when event = "InsertEnter" and I reload a file via :e or :e %
> ...

And analyzing this error, I think it is because in your `tsconfig.json` file of your Astro project, you are adding the comment `// Alias 'src' to '~'`, but JSON does not support comments, so is interrupted. some of the new features introduced (9b0d948) in this plugin and thus also break syntax coloring (plain text).

I suggest you remove such comment (or all the ones it contains) and avoid adding comments in JSON files, the reason? I leave you a [small article](https://www.freecodecamp.org/news/comments-in-json/) about this small reason and foundation :)

**Comment by frankjonen** [comment]
Not sure where you're getting the JSON stuff from. It's [this project](https://astro.build/themes/details/astro-landing-page/) without any changes so far. With `lazy = false` it works in the preview but not in the editor. `event = "BufEnter *.astro"` doesn't preview but work in editor. Both `BufEnter` and `InsertEnter` lines trigger the Error I pasted before.

**Comment by wuelnerdotexe** [comment]
Well, @frankjonen - please, the **FIRST** thing you have to do is remove [this comment](https://github.com/mhyfritz/astro-landing-page/blob/ba3b99d8458107b0aeb5a9ffc5f71cc3bfb4a9f0/tsconfig.json#L4) from the `tsconfig.json` of your project. The plugin should still run correctly with `lazy = false`, but if it works fine with `event = "BufEnter *.astro"`, I recommend you instead try `event = { "BufNewFile *.astro", "BufRead *.astro" }`.

**Comment by frankjonen** [comment]
Thanks for insisting on the JSON comments @wuelnerdotexe. That did it.
While I don't understand why a syntax error in one file has an influence on the plug-in working on other files, it did resolve the issue. I don't think I ever had comments in my own JSON files though. So much for NeoVim making things easier.

As a recap, this works:

```lua
  {
    "wuelnerdotexe/vim-astro",
    lazy = false,
  },
```

Would be nice to have it lazy-load in the future though as this seems to be important for performance in NeoVim. No idea. In regular Vim it just figured that stuff out on its own.

**Comment by wuelnerdotexe** [comment]
Hi! @frankjonen - glad to hear your issue has been resolved.

This plugin scans all paths specified in your `tsconfig.json` to provide native Vim functionality like "go to file" and "go to definition" etc. for his Astro project; That's why it breaks when your `tsconfig.json` contains syntax errors, like comments for example.

Lastly, lazy loading this plugin should work perfectly with `ft = "astro"` but it seems that [`lazy.nvim`](https://github.com/folke/lazy.nvim) is not optimized for VimScript syntax files :/

**Comment by wuelnerdotexe** [comment]
Could you please close this issue if it now works as it should? Thanks in advance :)

**Comment by frankjonen** [comment]
I didn't even know that you can scan relative paths in Vim plugins.
Thanks for your work on this and your help. Closing now.
